// Unit icon SVG system
// Lines 5689-5951 from shooting-resolver165.jsx

// ━━━ UNIT ICON SYSTEM ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

function getUnitIconType(name) {
  const n = name.toLowerCase();
  if (n.includes("primarch") || n.includes("lion el") || n.includes("jaghatai") || n.includes("leman russ") || n.includes("rogal dorn") || n.includes("sanguinius") || n.includes("ferrus") || n.includes("guilliman") || n.includes("vulkan") || n.includes("corax") || n.includes("fulgrim") || n.includes("perturabo") || n.includes("curze") || n.includes("angron") || n.includes("lorgar") || n.includes("mortarion") || n.includes("magnus") || n.includes("horus") || n.includes("alpharius")) return "primarch";
  if (n.includes("daemon")) return "daemon";
  if (n.includes("saturnine") && n.includes("dread")) return "dreadnought";
  // HQ characters - must check before terminator matching
  if (n.includes("praetor") || n.includes("centurion") || n.includes("magos") || n.includes("commander") || n.includes("champion") || n.includes("chaplain") || n.includes("librarian") || n.includes("moritat") || n.includes("herald") || n.includes("vigilator") || n.includes("forge lord") || n.includes("siege breaker") || n.includes("master of signal") || n.includes("apothecary")) return "commander";
  if (n.includes("cataphractii") || n.includes("tartaros") || n.includes("fulmentarus") || n.includes("aquilon") || n.includes("saturnine") || n.includes("terminator")) return "terminator";
  if (n.includes("contemptor") || n.includes("leviathan") || n.includes("deredeo") || n.includes("castra ferrum")) return "dreadnought";
  if (n.includes("predator") || n.includes("sicaran") || n.includes("land raider") || n.includes("spartan") || n.includes("proteus") || n.includes("leman russ") || n.includes("malcador") || n.includes("vindicator") || n.includes("araknae")) return "tank";
  if (n.includes("whirlwind") || n.includes("basilisk") || n.includes("medusa") || n.includes("rapier") || n.includes("thanatar")) return "artillery";
  if (n.includes("caladius") || n.includes("pallas")) return "grav_tank";
  if (n.includes("agamatus") || n.includes("jetbike") || n.includes("scimitar")) return "jetbike";
  if (n.includes("xiphon") || n.includes("storm eagle") || n.includes("fire raptor")) return "flyer";
  if (n.includes("javelin") || n.includes("land speeder")) return "grav_tank";
  if (n.includes("telemon")) return "heavy_dread";
  if (n.includes("castellax") || n.includes("vorax") || n.includes("thallax") || n.includes("krios") || n.includes("scyllax") || n.includes("automata")) return "automata";
  if (n.includes("myrmidon") || n.includes("ursarax")) return "tech_elite";
  if (n.includes("tech-thrall") || n.includes("adsecularis")) return "thrall";
  if (n.includes("custodian") || n.includes("sagittarum") || n.includes("sentinel guard") || n.includes("tribune")) return "custodes";
  if (n.includes("ogryn") || n.includes("charonite")) return "ogryn";
  if (n.includes("destroyer")) return "destroyer";
  if (n.includes("recon")) return "recon";
  if (n.includes("seeker")) return "seeker";
  if (n.includes("breacher")) return "breacher";
  if (n.includes("assault") || n.includes("despoiler")) return "assault";
  return "infantry";
}

function UnitIcon({ type, size = 36, color = "#8b6508" }) {
  const s = size;
  const icons = {
    infantry: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("circle", {"cx": "18", "cy": "7", "r": "4", "fill": color, "opacity": "0.9"}), React.createElement("rect", {"x": "14", "y": "12", "width": "8", "height": "12", "rx": "2", "fill": color, "opacity": "0.8"}), React.createElement("rect", {"x": "11", "y": "24", "width": "5", "height": "8", "rx": "1.5", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "20", "y": "24", "width": "5", "height": "8", "rx": "1.5", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "22", "y": "13", "width": "10", "height": "3", "rx": "1", "fill": color, "opacity": "0.6", "transform": "rotate(-15 27 14)"}), React.createElement("rect", {"x": "7", "y": "14", "width": "7", "height": "5", "rx": "1", "fill": color, "opacity": "0.5"}))
    ),
    terminator: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("circle", {"cx": "18", "cy": "6", "r": "4.5", "fill": color, "opacity": "0.9"}), React.createElement("path", {"d": "M10 11 H26 L28 14 V26 L24 28 H12 L8 26 V14 Z", "fill": color, "opacity": "0.8"}), React.createElement("rect", {"x": "10", "y": "28", "width": "6", "height": "7", "rx": "2", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "20", "y": "28", "width": "6", "height": "7", "rx": "2", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "4", "y": "12", "width": "6", "height": "8", "rx": "2", "fill": color, "opacity": "0.6"}), React.createElement("rect", {"x": "26", "y": "12", "width": "6", "height": "8", "rx": "2", "fill": color, "opacity": "0.6"}), React.createElement("rect", {"x": "28", "y": "11", "width": "8", "height": "3", "rx": "1", "fill": color, "opacity": "0.5"}))
    ),
    dreadnought: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("rect", {"x": "12", "y": "2", "width": "12", "height": "8", "rx": "2", "fill": color, "opacity": "0.9"}), React.createElement("rect", {"x": "8", "y": "10", "width": "20", "height": "16", "rx": "3", "fill": color, "opacity": "0.85"}), React.createElement("circle", {"cx": "18", "cy": "17", "r": "4", "fill": color, "opacity": "0.5"}), React.createElement("rect", {"x": "3", "y": "11", "width": "5", "height": "14", "rx": "2", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "28", "y": "11", "width": "5", "height": "14", "rx": "2", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "0", "y": "12", "width": "5", "height": "3", "rx": "1", "fill": color, "opacity": "0.55"}), React.createElement("rect", {"x": "10", "y": "26", "width": "6", "height": "8", "rx": "2", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "20", "y": "26", "width": "6", "height": "8", "rx": "2", "fill": color, "opacity": "0.7"}))
    ),
    heavy_dread: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("rect", {"x": "11", "y": "1", "width": "14", "height": "9", "rx": "2", "fill": color, "opacity": "0.9"}), React.createElement("rect", {"x": "6", "y": "10", "width": "24", "height": "17", "rx": "3", "fill": color, "opacity": "0.85"}), React.createElement("circle", {"cx": "18", "cy": "17", "r": "5", "fill": color, "opacity": "0.5"}), React.createElement("rect", {"x": "1", "y": "10", "width": "5", "height": "16", "rx": "2", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "30", "y": "10", "width": "5", "height": "16", "rx": "2", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "8", "y": "27", "width": "8", "height": "8", "rx": "2", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "20", "y": "27", "width": "8", "height": "8", "rx": "2", "fill": color, "opacity": "0.7"}))
    ),
    tank: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("rect", {"x": "4", "y": "16", "width": "28", "height": "12", "rx": "3", "fill": color, "opacity": "0.85"}), React.createElement("rect", {"x": "10", "y": "8", "width": "16", "height": "10", "rx": "2", "fill": color, "opacity": "0.8"}), React.createElement("rect", {"x": "22", "y": "4", "width": "14", "height": "4", "rx": "1", "fill": color, "opacity": "0.65"}), React.createElement("ellipse", {"cx": "8", "cy": "30", "rx": "4", "ry": "3", "fill": color, "opacity": "0.6"}), React.createElement("ellipse", {"cx": "18", "cy": "30", "rx": "4", "ry": "3", "fill": color, "opacity": "0.6"}), React.createElement("ellipse", {"cx": "28", "cy": "30", "rx": "4", "ry": "3", "fill": color, "opacity": "0.6"}), React.createElement("rect", {"x": "4", "y": "28", "width": "28", "height": "4", "rx": "2", "fill": color, "opacity": "0.5"}))
    ),
    artillery: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("rect", {"x": "6", "y": "14", "width": "24", "height": "10", "rx": "3", "fill": color, "opacity": "0.8"}), React.createElement("rect", {"x": "14", "y": "6", "width": "12", "height": "10", "rx": "2", "fill": color, "opacity": "0.75"}), React.createElement("rect", {"x": "20", "y": "1", "width": "16", "height": "5", "rx": "1.5", "fill": color, "opacity": "0.6", "transform": "rotate(10 28 3)"}), React.createElement("ellipse", {"cx": "10", "cy": "28", "rx": "5", "ry": "4", "fill": color, "opacity": "0.6"}), React.createElement("ellipse", {"cx": "26", "cy": "28", "rx": "5", "ry": "4", "fill": color, "opacity": "0.6"}), React.createElement("rect", {"x": "6", "y": "24", "width": "24", "height": "5", "rx": "2", "fill": color, "opacity": "0.5"}))
    ),
    grav_tank: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("ellipse", {"cx": "18", "cy": "22", "rx": "16", "ry": "7", "fill": color, "opacity": "0.75"}), React.createElement("rect", {"x": "10", "y": "10", "width": "16", "height": "12", "rx": "4", "fill": color, "opacity": "0.85"}), React.createElement("rect", {"x": "22", "y": "6", "width": "12", "height": "4", "rx": "1", "fill": color, "opacity": "0.6"}), React.createElement("ellipse", {"cx": "18", "cy": "32", "rx": "12", "ry": "2", "fill": color, "opacity": "0.3"}))
    ),
    jetbike: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("circle", {"cx": "18", "cy": "8", "r": "3.5", "fill": color, "opacity": "0.9"}), React.createElement("path", {"d": "M12 12 H24 L28 18 L24 22 H12 L4 18 Z", "fill": color, "opacity": "0.75"}), React.createElement("ellipse", {"cx": "18", "cy": "28", "rx": "14", "ry": "4", "fill": color, "opacity": "0.5"}), React.createElement("rect", {"x": "6", "y": "22", "width": "24", "height": "6", "rx": "3", "fill": color, "opacity": "0.65"}), React.createElement("rect", {"x": "24", "y": "13", "width": "8", "height": "3", "rx": "1", "fill": color, "opacity": "0.5"}))
    ),
    automata: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("rect", {"x": "12", "y": "2", "width": "12", "height": "8", "rx": "1", "fill": color, "opacity": "0.9"}), React.createElement("circle", {"cx": "15", "cy": "6", "r": "2", "fill": color, "opacity": "0.4"}), React.createElement("circle", {"cx": "21", "cy": "6", "r": "2", "fill": color, "opacity": "0.4"}), React.createElement("rect", {"x": "9", "y": "10", "width": "18", "height": "14", "rx": "2", "fill": color, "opacity": "0.8"}), React.createElement("rect", {"x": "4", "y": "11", "width": "5", "height": "12", "rx": "1", "fill": color, "opacity": "0.65"}), React.createElement("rect", {"x": "27", "y": "11", "width": "5", "height": "12", "rx": "1", "fill": color, "opacity": "0.65"}), React.createElement("rect", {"x": "11", "y": "24", "width": "6", "height": "10", "rx": "1.5", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "19", "y": "24", "width": "6", "height": "10", "rx": "1.5", "fill": color, "opacity": "0.7"}))
    ),
    tech_elite: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("circle", {"cx": "18", "cy": "7", "r": "4", "fill": color, "opacity": "0.9"}), React.createElement("rect", {"x": "13", "y": "12", "width": "10", "height": "12", "rx": "2", "fill": color, "opacity": "0.8"}), React.createElement("circle", {"cx": "18", "cy": "17", "r": "3", "fill": color, "opacity": "0.4"}), React.createElement("rect", {"x": "11", "y": "24", "width": "5", "height": "8", "rx": "1.5", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "20", "y": "24", "width": "5", "height": "8", "rx": "1.5", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "5", "y": "10", "width": "8", "height": "4", "rx": "1", "fill": color, "opacity": "0.5"}), React.createElement("rect", {"x": "23", "y": "10", "width": "8", "height": "4", "rx": "1", "fill": color, "opacity": "0.5"}), React.createElement("circle", {"cx": "9", "cy": "12", "r": "2", "fill": color, "opacity": "0.6"}), React.createElement("circle", {"cx": "27", "cy": "12", "r": "2", "fill": color, "opacity": "0.6"}))
    ),
    custodes: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("circle", {"cx": "18", "cy": "6", "r": "4", "fill": color, "opacity": "0.9"}), React.createElement("path", {"d": "M18 1 L20 4 L18 3 L16 4 Z", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "13", "y": "11", "width": "10", "height": "13", "rx": "2", "fill": color, "opacity": "0.85"}), React.createElement("rect", {"x": "11", "y": "24", "width": "5", "height": "9", "rx": "1.5", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "20", "y": "24", "width": "5", "height": "9", "rx": "1.5", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "22", "y": "12", "width": "10", "height": "2.5", "rx": "1", "fill": color, "opacity": "0.6"}), React.createElement("rect", {"x": "6", "y": "8", "width": "3", "height": "18", "rx": "1", "fill": color, "opacity": "0.5"}), React.createElement("polygon", {"points": "7.5,4 9,8 6,8", "fill": color, "opacity": "0.6"}))
    ),
    commander: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("circle", {"cx": "18", "cy": "7", "r": "4.5", "fill": color, "opacity": "0.9"}), React.createElement("path", {"d": "M14 2 L18 0 L22 2 L20 5 H16 Z", "fill": color, "opacity": "0.65"}), React.createElement("rect", {"x": "13", "y": "12", "width": "10", "height": "13", "rx": "2", "fill": color, "opacity": "0.85"}), React.createElement("rect", {"x": "11", "y": "25", "width": "5", "height": "8", "rx": "1.5", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "20", "y": "25", "width": "5", "height": "8", "rx": "1.5", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "23", "y": "14", "width": "9", "height": "3", "rx": "1", "fill": color, "opacity": "0.6"}), React.createElement("rect", {"x": "4", "y": "13", "width": "9", "height": "6", "rx": "1", "fill": color, "opacity": "0.5"}))
    ),
    primarch: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("circle", {"cx": "18", "cy": "5", "r": "4.5", "fill": color, "opacity": "0.95"}), React.createElement("path", {"d": "M12 0 L18 -2 L24 0 L21 4 H15 Z", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "11", "y": "10", "width": "14", "height": "15", "rx": "2", "fill": color, "opacity": "0.9"}), React.createElement("rect", {"x": "10", "y": "25", "width": "6", "height": "10", "rx": "2", "fill": color, "opacity": "0.75"}), React.createElement("rect", {"x": "20", "y": "25", "width": "6", "height": "10", "rx": "2", "fill": color, "opacity": "0.75"}), React.createElement("rect", {"x": "4", "y": "10", "width": "7", "height": "10", "rx": "2", "fill": color, "opacity": "0.6"}), React.createElement("rect", {"x": "25", "y": "10", "width": "7", "height": "10", "rx": "2", "fill": color, "opacity": "0.6"}), React.createElement("rect", {"x": "28", "y": "8", "width": "8", "height": "3", "rx": "1", "fill": color, "opacity": "0.5"}))
    ),
    daemon: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("circle", {"cx": "18", "cy": "8", "r": "5", "fill": color, "opacity": "0.9"}), React.createElement("path", {"d": "M12 4 L10 0 L14 5 Z", "fill": color, "opacity": "0.7"}), React.createElement("path", {"d": "M24 4 L26 0 L22 5 Z", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "12", "y": "13", "width": "12", "height": "13", "rx": "2", "fill": color, "opacity": "0.8"}), React.createElement("rect", {"x": "10", "y": "26", "width": "6", "height": "9", "rx": "2", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "20", "y": "26", "width": "6", "height": "9", "rx": "2", "fill": color, "opacity": "0.7"}), React.createElement("path", {"d": "M6 14 Q4 20 6 26", "stroke": color, "strokeWidth": "2", "fill": "none", "opacity": "0.5"}), React.createElement("path", {"d": "M30 14 Q32 20 30 26", "stroke": color, "strokeWidth": "2", "fill": "none", "opacity": "0.5"}))
    ),
    ogryn: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("circle", {"cx": "18", "cy": "6", "r": "5", "fill": color, "opacity": "0.9"}), React.createElement("rect", {"x": "10", "y": "11", "width": "16", "height": "14", "rx": "3", "fill": color, "opacity": "0.85"}), React.createElement("rect", {"x": "9", "y": "25", "width": "7", "height": "10", "rx": "2", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "20", "y": "25", "width": "7", "height": "10", "rx": "2", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "4", "y": "12", "width": "6", "height": "10", "rx": "2", "fill": color, "opacity": "0.6"}), React.createElement("rect", {"x": "26", "y": "12", "width": "6", "height": "10", "rx": "2", "fill": color, "opacity": "0.6"}))
    ),
    thrall: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("circle", {"cx": "18", "cy": "8", "r": "3.5", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "14", "y": "12", "width": "8", "height": "11", "rx": "1.5", "fill": color, "opacity": "0.6"}), React.createElement("rect", {"x": "12", "y": "23", "width": "5", "height": "8", "rx": "1", "fill": color, "opacity": "0.5"}), React.createElement("rect", {"x": "19", "y": "23", "width": "5", "height": "8", "rx": "1", "fill": color, "opacity": "0.5"}), React.createElement("rect", {"x": "22", "y": "14", "width": "8", "height": "2", "rx": "1", "fill": color, "opacity": "0.4"}))
    ),
    destroyer: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("circle", {"cx": "18", "cy": "7", "r": "4", "fill": color, "opacity": "0.9"}), React.createElement("rect", {"x": "14", "y": "12", "width": "8", "height": "12", "rx": "2", "fill": color, "opacity": "0.8"}), React.createElement("rect", {"x": "11", "y": "24", "width": "5", "height": "8", "rx": "1.5", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "20", "y": "24", "width": "5", "height": "8", "rx": "1.5", "fill": color, "opacity": "0.7"}), React.createElement("circle", {"cx": "18", "cy": "18", "r": "2", "fill": color, "opacity": "0.4"}), React.createElement("rect", {"x": "22", "y": "11", "width": "12", "height": "4", "rx": "1", "fill": color, "opacity": "0.6"}), React.createElement("circle", {"cx": "33", "cy": "13", "r": "2", "fill": color, "opacity": "0.5"}))
    ),
    recon: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("circle", {"cx": "18", "cy": "7", "r": "3.5", "fill": color, "opacity": "0.85"}), React.createElement("rect", {"x": "14", "y": "11", "width": "8", "height": "11", "rx": "2", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "12", "y": "22", "width": "5", "height": "9", "rx": "1.5", "fill": color, "opacity": "0.6"}), React.createElement("rect", {"x": "19", "y": "22", "width": "5", "height": "9", "rx": "1.5", "fill": color, "opacity": "0.6"}), React.createElement("rect", {"x": "20", "y": "8", "width": "14", "height": "2.5", "rx": "1", "fill": color, "opacity": "0.5"}), React.createElement("circle", {"cx": "14", "cy": "5", "r": "2", "fill": color, "opacity": "0.4"}))
    ),
    seeker: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("circle", {"cx": "18", "cy": "7", "r": "4", "fill": color, "opacity": "0.9"}), React.createElement("rect", {"x": "14", "y": "12", "width": "8", "height": "12", "rx": "2", "fill": color, "opacity": "0.8"}), React.createElement("rect", {"x": "11", "y": "24", "width": "5", "height": "8", "rx": "1.5", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "20", "y": "24", "width": "5", "height": "8", "rx": "1.5", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "22", "y": "10", "width": "13", "height": "3", "rx": "1", "fill": color, "opacity": "0.6"}), React.createElement("circle", {"cx": "34", "cy": "11.5", "r": "1.5", "fill": color, "opacity": "0.4"}), React.createElement("path", {"d": "M16 3 L18 1 L20 3", "stroke": color, "strokeWidth": "1", "fill": "none", "opacity": "0.5"}))
    ),
    breacher: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("circle", {"cx": "18", "cy": "7", "r": "4", "fill": color, "opacity": "0.9"}), React.createElement("rect", {"x": "14", "y": "12", "width": "8", "height": "12", "rx": "2", "fill": color, "opacity": "0.8"}), React.createElement("rect", {"x": "11", "y": "24", "width": "5", "height": "8", "rx": "1.5", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "20", "y": "24", "width": "5", "height": "8", "rx": "1.5", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "4", "y": "8", "width": "10", "height": "16", "rx": "2", "fill": color, "opacity": "0.55"}), React.createElement("rect", {"x": "23", "y": "14", "width": "8", "height": "2.5", "rx": "1", "fill": color, "opacity": "0.5"}))
    ),
    assault: (
      React.createElement("svg", {"width": s, "height": s, "viewBox": "0 0 36 36", "fill": "none"}, React.createElement("circle", {"cx": "18", "cy": "7", "r": "4", "fill": color, "opacity": "0.9"}), React.createElement("rect", {"x": "14", "y": "12", "width": "8", "height": "12", "rx": "2", "fill": color, "opacity": "0.8"}), React.createElement("rect", {"x": "11", "y": "24", "width": "5", "height": "8", "rx": "1.5", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "20", "y": "24", "width": "5", "height": "8", "rx": "1.5", "fill": color, "opacity": "0.7"}), React.createElement("rect", {"x": "8", "y": "6", "width": "4", "height": "14", "rx": "1", "fill": color, "opacity": "0.5", "transform": "rotate(-20 10 13)"}), React.createElement("rect", {"x": "22", "y": "14", "width": "8", "height": "2.5", "rx": "1", "fill": color, "opacity": "0.5"}))
    ),
  };
  return icons[type] || icons.infantry;
}

